### PR TITLE
An alternative Arabic translation.

### PR DESCRIPTION
**Pull request by ghost**
The current translation is perfectly grammatical and does carry the full meaning of the original quote. However, it is too literal, akin more to a Google translation than a native one. You wouldn't come across such a sentence in a book or newspaper for instance. The one I'm proposing in the other hand is more like a real-world rendition of the quote. I hope that people with a good grasp on Arabic would also weigh in on this.

### CODE REVIEW

**Comment by Husamdababneh** [comment]
@tellela If i may note , there is an incorrect letter,
 'ض' 
should be
 'ظ'

NOTE: Sorry i cannot edit it myself I'm on the phone, If i got near a PC I'll submit my contribution

**Comment by ghost** [comment]
That's right @Husamdababneh. Submit your correction when you can.

**Comment by cmuratori** [comment]
Unfortunately I am not in a position to judge, since I am not a native speaker.  I would add, however, that the goal here is to have as much "decoration" on the characters as possible; for example, the German version is intentionally wordy so that more diacritical marks can be added.  So please keep that in mind.

\- Casey

**Comment by ghost** [comment]
In that case, the current translation is fine. Just make sure to move the period to the left of the sentence.

**Comment by cmuratori** [comment]
I'm still really confused about the "left of the sentence" part.  I was under the impression that in the C file, it remains LTR, so the period should go on the right side, and then the terminal flips it.  Does it actually go RTL in the C file as well?

\- Casey

**Comment by ghost** [comment]
Let's discuss the period in the other pull request.

**Comment by cmuratori** [comment]
OK.

\- Casey

**Pull request closed without merging**
