### PR TITLE
Fixed German and added Bulgarian 

### PR DESCRIPTION
**Pull request by Wassimulator**
German was wordy and unnatural. Added Bulgarian from a known native.

### CODE REVIEW

**Comment by cmuratori** [comment]
I think the German should be left as-is - it was intentionally wordy in order to use all the diacritical marks, IIRC.  Would you like to alter this request to just add the Bulgarian?

\- Casey

**Comment by Wassimulator** [comment]
Yeah I edited it; just Bulgarian then.

Wassim

**Comment by cmuratori** [comment]
Looks like this may have to get resubmitted?  For some reason it still thinks it's conflicting.... you might want to try doing it again.  Normally I would do the merge, but, if it's anything other than a clean addition, I don't want to touch it because I can't actually _read_ any of these lines :)

\- Casey

**Comment by Wassimulator** [comment]
Done.

**Pull request closed without merging**
