### PR TITLE
Move the period to end of sentence in Arabic translation.

### PR DESCRIPTION
**Pull request by ghost**
Since Arabic is a Right To Left language, the period appears to the left of the sentence.

### CODE REVIEW

**Comment by cmuratori** [comment]
Not sure I understand this - although these are in an LTR file, when they are printed out by the terminal, they are reversed.  I don't think you move the period; the terminal moves the period.  Am I wrong?

\- Casey

**Comment by ghost** [comment]
In the picture included in your tweet (link below), the period in the right-most position of the sentence; it should be in the left-most position.

https://twitter.com/cmuratori/status/1416978255584792579

**Comment by cmuratori** [comment]
Yes, but that is correct. refterm currently doesn't handle punctuation properly in RTL - this is an open issue.  So that is the correct behavior of termbench, in that it is clearly showing refterm has a bug, which is the goal.  We don't want to correct problems that show up in terminals, we want them to be clearly visible!

\- Casey

**Comment by ghost** [comment]
Ohh! I wasn't aware of that. I'm so sorry for all this hassle!

**Comment by cmuratori** [comment]
No worries.  refterm is passable at RTL right now but it's not great.  In the future I will upgrade it to try to ensure 100% BIDI compliance, but right now it calls Uniscribe and Uniscribe is pretty crappy, so it's kind of limping along with complex scripts at the moment due to that constraint.

\- Casey

**Pull request closed without merging**
