### PR TITLE
termbench: Compiling for Mac M1

### PR DESCRIPTION
**Pull request by GeorgeLS**
This PR adds support for M1 Macs. I have extracted the process of obtaining the CPU name into a
separate function to make a little bit more clean as the M1 doesn't need the loop.
I also omitted the inclusion of cpuid.h in case of M1 as it was throwing a compiler error "This is only for x86".
I guess that this has only inline asm for intel cpus.

Edit: I didn't know if I should open this PR against master or V3 so I went with master. If you want me to change that, feel free to tell me :)

### CODE REVIEW

**Comment by GeorgeLS** [comment]
Side note: You can add another terminal in your crash list. Mac's default terminal crashed when I run this :D

**Comment by cmuratori** [comment]
Sorry to do this to you, but, er... could you do this on the v3_work branch instead??  We already have M1 support in there AFAIK, but I think your system string is better than the one that was contributed... if you wouldn't mind taking a look at that, I would much prefer to have v3 correct since v2 is going to be yesterday's news shortly :)

\- Casey

**Comment by GeorgeLS** [comment]
I have merged v3_work to my master in order not to close this PR and open a new one. I have changed the system config string to retrieve the cpu brand. Not sure why github diff shows changes in README.md file but seems fine.

If you need any further changes let me know.

**Comment by cmuratori** [comment]
Awesome!  Thanks.

\- Casey

**Pull request merged**
